---
# Join Swarm Cluster
- hosts: all
  vars:
    host_addr: ""

  tasks:  
    - name: CMD to join swarm as worker
      command: docker swarm join-token -q worker
      register: cmd_worker
      delegate_to: "{{ host_addr }}"
      
    - name: Join Swarm Cluster as Worker
      command: docker swarm join --token {{ cmd_worker.stdout }} X.X.X.X:2377
      
